version: "3.1"

services:
  client:
    restart: always
    build:
      context: client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
      - socket
    networks:
      - app-network
    ports:
      - "5173:80"
  server:
    restart: always
    build:
      context: server
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "3000:3000"
  socket:
    restart: always
    build:
      context: socket
    volumes:
      - ./socket:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
    networks:
      - app-network
    ports:
      - "3030:3030"
  db:
    restart: always
    image: mongo:6.0.13
    volumes:
      - ./data:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"
networks:
  app-network:
