version: "3.1"

services:
  # client:
  #   build:
  #     context: client
  #     target: development
  #   ports:
  #     - 3000:3000
  #   stdin_open: true
  #   volumes:
  #     - ./client:/usr/src/app
  #     - /usr/src/app/node_modules
  #   restart: always
  #   networks:
  #     - react-express
  #   depends_on:
  #     - server

  server:
    restart: always
    build:
      context: server
      target: development
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - express-mongo
      # - react-express
    ports:
      - "3000:3000"
    expose:
      - 3000
  db:
    restart: always
    image: mongo:6.0.13
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    ports:
      - "27017:27017"
    expose:
      - 27017
networks:
  # react-express:
  express-mongo:
